# <center>Tarefa 1</center>

### 1. Monte um passo a passo para o Bagging:

#### Primeiro passo

<p>Após obter o Dataset, após definir o problema e o modelo que será utilizado, devemos fornecer os números de estimadores, e cada estimador receberá uma amostra diferente, podendo repetir as amostras. Caso tenhamos escolhidos 5 estimadores, 5 tipos de amostras serão coletados.</p>

#### Segundo passo

<p>Nos 5 estimadores escolhidos, com amostras diferentes serão aplicados os modelos, gerando um resultado.</p>

#### Terceiro passo

<p>Após obtermos os resultados, caso for um problema de classificação, é eleito democraticamente, e o que tiver mais "votos" é o que será escolhido. Já um problema de regressão, é tirada a média dos valores que foram gerados.</p>

### 2. Explique com suas palavras o Bagging

<p>Bagging é um modelo que após escolher N amostras com reposição de um dataset, executa um modelo de machine learning, dependendo do tipo de problema. Caso classificação o mais abundante é escolhido, e o de regressão é tirada a média dos valores</p>

### 3. Implementar em python o código do Bagging

In [16]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

df = pd.read_csv('The Top Billionaires.csv')
df

NAME   2018   2019   2020   2021   2022
0        Elon Musk   19.9   22.3   24.6  151.0  219.0
1       Jeff Bezos  112.0  131.0  113.0  177.0  171.0
2  Bernard Arnault   72.0   76.0   76.0  150.0  158.0
3       Bill Gates   90.0   96.5   98.0  124.0  129.0
4   Warren Buffett   84.0   82.5   67.5   96.0  118.0
5       Larry Page   48.8   50.8   50.9   91.5  111.0
6      Sergey Brin   47.5   49.8   49.1   89.0  107.0
7    Larry Ellison   58.5   62.5   59.0   93.0  106.0
8    Steve Ballmer   38.4   41.2   52.7   68.7   91.4
9    Mukesh Ambani   40.1   50.0   36.8   84.5   90.7

In [21]:
# Bootstrap

x = df[['2018','2019','2020','2021']]
y = df['2022']

df1 = df.sample(n=5, random_state=1)
x1 = df1[['2018','2019','2020','2021']]
y1 = df1['2022']

df2 = df.sample(n=5, random_state=2)
x2 = df2[['2018','2019','2020','2021']]
y2 = df2['2022']

df3 = df.sample(n=5, random_state=3)
x3 = df3[['2018','2019','2020','2021']]
y3 = df3['2022']

In [25]:
model = LinearRegression()
model.fit(x, y)


LinearRegression()

In [26]:
r1 = model.score(x1, y1)
r1

0.9497056332658085

In [27]:
r2 = model.score(x2, y2)
r2

0.9809631271719222

In [28]:
r3 = model.score(x3, y3)
r3

0.8980574422815029

In [30]:
model.predict(x1)

array([176.21247987,  97.16773681, 110.77521946, 110.93329022,
       209.3416998 ])

In [33]:
y1

2    158.0
9     90.7
6    107.0
4    118.0
0    219.0
Name: 2022, dtype: float64

In [31]:
model.predict(x2)

array([110.93329022, 165.63431679, 113.81588613, 209.3416998 ,
       107.41898191])

In [32]:
y2

4    118.0
1    171.0
5    111.0
0    219.0
7    106.0
Name: 2022, dtype: float64

In [34]:
model.predict(x3)

array([113.81588613, 110.93329022, 165.63431679, 176.21247987,
        97.16773681])

In [35]:
y3

5    111.0
4    118.0
1    171.0
2    158.0
9     90.7
Name: 2022, dtype: float64